src/ControlsTest/Controllers/GridTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MvcControlsToolkit.Controllers;
using MvcControlsToolkit.Core.Business.Utilities;
using ControlsTest.Models;
using Microsoft.Extensions.Localization;
using Microsoft.AspNetCore.Http;
using ControlsTest.Data;
using MvcControlsToolkit.Core.OData;
using Microsoft.EntityFrameworkCore;
using MvcControlsToolkit.Core.Types;

namespace ControlsTest.Controllers
{
    public class GridTestController : ServerCrudController<ProductViewModelDetail, ProductViewModel, int?>
    {
        static GridTestController()
        {
            DefaultCRUDRepository<ApplicationDbContext, Product>
                .DeclareProjection<ProductViewModel>(
                    m => m.Maintenance == null ?
                    
                    new ProductViewModel
                    {
                        DateValid = m.DateValid == null ? null : (Month?)Month.FromDateTime(m.DateValid.Value)

                    } :

                    new ProductMaintenanceViewModel
                    {
                        DateValid = m.DateValid == null ? null : (Month?)Month.FromDateTime(m.DateValid.Value),
                        MaintenanceYearlyRate = (decimal)m.Maintenance.YearlyRate
                    }

                );
            DefaultCRUDRepository<ApplicationDbContext, Product>
               .DeclareQueryProjection(
                 m =>
                   new ProductViewModel()
                   {
                       DateValid = m.DateValid == null ? null : (Month?)Month.FromDateTime(m.DateValid.Value)

                   },
                   m => m.Id

               );
            DefaultCRUDRepository<ApplicationDbContext, Product>
                .DeclareProjection(
                    m => m.Maintenance != null ?
                    new ProductMaintenanceViewModelDetail
                    {
                        DateValid = m.DateValid == null ? null : (Month?)Month.FromDateTime(m.DateValid.Value),
                        MaintenanceYearlyRate = (decimal)m.Maintenance.YearlyRate
                    } :
                    new ProductViewModelDetail
                    {
                        DateValid = m.DateValid == null ? null : (Month?)Month.FromDateTime(m.DateValid.Value)

                    }

                );
            DefaultCRUDRepository<ApplicationDbContext, ProductType>
                .DeclareProjection<DisplayValue>(
                    m => new DisplayValue
                    {
                        Value = m.Id,
                        Display = m.Name
                    });

        }

        

        IWebQueryProvider queryProvider;
        private readonly ICRUDRepository TypesRepository;
        private IWebQueryable oDataRepository;
        public GridTestController(
            Data.ApplicationDbContext db, 
            IStringLocalizerFactory factory, 
            IHttpContextAccessor accessor, 
            IWebQueryProvider queryProvider) :base(factory, accessor)
        {
            //in actual 3 layers applications repository inherit 
            //from DefaultCRUDRepository
            //and then it is DI injected
            Repository = DefaultCRUDRepository.Create(db, db.Products);
            oDataRepository = new DefaultWebQueryRepository(Repository);
            TypesRepository = DefaultCRUDRepository.Create(db, db.ProductTypes);
            this.queryProvider = queryProvider;
        }
        public override string DetailColumnAdjustView
        {
            get
            {
                return "_DetailRows";
            }
        }
        public async Task<IActionResult> Index(int? page)
        {
            var query = queryProvider?.Parse<ProductViewModel>();
            int pg = page.HasValue ? page.Value : 1;
            if (pg < 1) pg = 1;

            var res = await Repository.GetPage<ProductViewModel>(
                query?.GetFilterExpression(),
                q => q.OrderBy(m => m.Name),
                pg, 3);
            var model = new ProductlistViewModel
            {
               

                Products = res
            };
            return View(model);
            
            
        }
        public async Task<IActionResult> IndexPartial(int? page)
        {
            var query = queryProvider?.Parse<ProductViewModel>();
            int pg = page.HasValue ? page.Value : 1;
            if (pg < 1) pg = 1;

            var model = new ProductlistViewModel
            {
                Products = await Repository.GetPage<ProductViewModel>(
                query?.GetFilterExpression(),
                q => q.OrderBy(m => m.Name),
                pg, 3)
            };
            var res = PartialView("_gridIndex", model);
            return res;


        }
        public async Task<IActionResult> IndexEdit()
        {
            var query=queryProvider.Parse<ProductViewModel>();
            
            int pg = (int)query.Page;
            var grouping = query.GetGrouping<ProductViewModelGrouping>();

            ProductlistViewModel model = new ProductlistViewModel
                {
                Query = query,
                Products =
                    grouping == null ?
                        await Repository.GetPage(
                            query.GetFilterExpression(),
                            query.GetSorting() ??
                                (q => q.OrderBy(m => m.Name)),
                            pg, 3)
                        :
                        await Repository.GetPageExtended(
                            query.GetFilterExpression(),
                            query.GetSorting<ProductViewModelGrouping>() ?? 
                                (q => q.OrderBy(m => m.Name)),
                            pg, 3,
                            query.GetGrouping<ProductViewModelGrouping>())
                };


            ViewBag.AllTypes = (await TypesRepository.GetPage<DisplayValue>(null, m => m.OrderBy(n => n.Display), 1, 1000)).Data;

            return View(model);
        }
        public async Task<IActionResult> IndexEditDA()
        {
            queryProvider.OrderBy =
                queryProvider.OrderBy ?? "Name asc";
            queryProvider.Top = 
                queryProvider.Top??"3";
            var query = queryProvider.Parse<ProductViewModel>();

            ProductlistViewModel model = new ProductlistViewModel
            {
                Query = query,
                Products = await oDataRepository
                    .ExecuteQuery<ProductViewModel, ProductViewModelGrouping>
                        (queryProvider)
                   
            };


            ViewBag.AllTypes = (await TypesRepository.GetPage<DisplayValue>(null, m => m.OrderBy(n => n.Display), 1, 1000)).Data;

            return View(model);
        }
        public async Task<IActionResult> IndexEditDetail(int? page)
        {
            int pg = page.HasValue ? page.Value : 1;
            if (pg < 1) pg = 1;

            var model = new ProductlistViewModel
            {
                Products = await Repository.GetPage<ProductViewModel>(
                null,
                q => q.OrderBy(m => m.Name),
                pg, 3)
            };
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> IndexBatch(int? page)
        {
            int pg = page.HasValue ? page.Value : 1;
            if (pg < 1) pg = 1;

            var model = new ProductlistBatchViewModel
            {
                Products = await Repository.GetPage<ProductViewModel>(
                null,
                q => q.OrderBy(m => m.Name),
                pg, 3)
            };
            model.ModifiedProducts = model.Products.Data;
            return View(model);
        }
        public async Task<IActionResult> IndexBatchDetail(int? page)
        {
            int pg = page.HasValue ? page.Value : 1;
            if (pg < 1) pg = 1;

            var model = new ProductlistBatchViewModel
            {
                Products = await Repository.GetPage<ProductViewModel>(
                null,
                q => q.OrderBy(m => m.Name),
                pg, 3)
            };
            model.ModifiedProducts = model.Products.Data;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> IndexBatch(ProductlistBatchViewModel model)
        {
            if (ModelState.IsValid)
            {
                Repository.UpdateList(false, model.Products.Data, model.ModifiedProducts);
                await Repository.SaveChanges();
                return RedirectToAction("IndexBatch", new { page = model.Products.Page });
            }
            else
            {
                return View(model);
            }
        }
        [HttpPost]
        public async Task<IActionResult> IndexBatchDetail(ProductlistBatchViewModel model)
        {
            if (ModelState.IsValid)
            {
                Repository.UpdateList(false, model.Products.Data, model.ModifiedProducts);
                await Repository.SaveChanges();
                return RedirectToAction("IndexBatchDetail", new { page = model.Products.Page });
            }
            else
            {
                return View(model);
            }
        }
    }
    public class DetailTestController : Controller
    {
        private readonly DefaultCRUDRepository<ApplicationDbContext, Product> Repository;
        private readonly ICRUDRepository TypesRepository;
        static DetailTestController()
        {
            DefaultCRUDRepository<ApplicationDbContext, Product>
                .DeclareProjection<ProductViewModelDetail>(
                    m => m.Maintenance != null ?
                    new ProductMaintenanceViewModelDetail
                    {

src/ControlsTest/Views/Shared/_EnhancementFallbackPartial.cshtml
<script src="~/lib/smalot-bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script src="~/lib/seiyria-bootstrap-slider/dist/bootstrap-slider.min.js"></script>
<script src="~/lib/bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js"></script>
<script src="~/lib/mvcct-enhancer/mvcct.enhancer.min.js"></script>
<script src="~/lib/mvcct-enhancer/enhancer-modules/mvcct.enhancer.input.basic.min.js"></script>
<script src="~/lib/bootstrap-html5-fallback/bootstrap.html5.fallback.min.js"></script>
<script type="text/javascript">
        mvcct.enhancer.addBasicInput(Globalize);
</script>

src/ControlsTest/Views/Shared/_FallbackCss.cshtml
<link href="~/lib/seiyria-bootstrap-slider/dist/css/bootstrap-slider.min.css" rel="stylesheet" />
<link href="~/lib/smalot-bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
<link href="~/lib/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css" rel="stylesheet" />

src/ControlsTest/Views/Shared/_GlobalizationScriptsPartial.cshtml
@using System.Globalization
<script src="~/lib/globalize/globalize.min.js"></script>
<script type="text/javascript">
    @{var culture = CultureInfo.CurrentCulture.Name; }
    (function () {

        $.when(
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/supplemental/likelysubtags.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/supplemental/numberingSystems.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/supplemental/timeData.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/supplemental/weekData.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/supplemental/currencyData.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/main/" + culture + "/currencies.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/main/" + culture + "/numbers.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/main/" + culture + "/ca-gregorian.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/main/" + culture + "/timeZoneNames.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/main/" + culture + "/dateFields.json")"),
          $.getJSON("@Url.Content("~/lib/globalize/cldr-data/main/" + culture + "/layout.json")")

        ).then(function () {
            // Normalize $.get results, we only need the JSON, not the request statuses.
            return [].slice.apply(arguments, [0]).map(function (result) {
                return result[0];
            });
        })
         .then(Globalize.load).then(function () {
             Globalize.locale("@culture");
             mvcct.enhancer.asyncReady();

         });

    })(jQuery);
</script>

src/ControlsTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ControlsTest</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @{ await Html.RenderPartialAsync("_FallbackCss"); }
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ControlsTest</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="AutocompleteTest">Autocomplete test</a></li>
                    <li><a asp-area="" asp-controller="GridTest" asp-action="Index">Immediate grid test </a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Grid tests<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="GridTest" asp-action="Index">Display only grid</a></li>
                            <li><a asp-area="" asp-controller="GridTest" asp-action="IndexEdit">Edit immediate grid </a></li>
                            <li><a asp-area="" asp-controller="GridTest" asp-action="IndexEditDA">Edit immediate grid (data annotations) </a></li>
                            <li><a asp-area="" asp-controller="GridTest" asp-action="IndexEditDetail">Edit detail immediate grid </a></li>
                            <li><a asp-area="" asp-controller="GridTest" asp-action="IndexBatch">Batch grid</a></li>
                            <li><a asp-area="" asp-controller="GridTest" asp-action="IndexBatchDetail">Batch detail grid </a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Detail tests<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="DetailTest" asp-action="Detail">Display Test </a></li>
                            <li><a asp-area="" asp-controller="DetailTest" asp-action="Edit">Edit Test </a></li>
                            <li><a asp-area="" asp-controller="DetailTest" asp-action="Create" asp-route-row="0">Create normal </a></li>
                            <li><a asp-area="" asp-controller="DetailTest" asp-action="Create"  asp-route-row="1">Create maintenance </a></li>
                        </ul>
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - ControlsTest</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @{ await Html.RenderPartialAsync("_GlobalizationScriptsPartial"); }
    @{ await Html.RenderPartialAsync("_EnhancementFallbackPartial"); }
    @RenderSection("scripts", required: false)
    <script src="~/startupjs/startup.min.js"></script>
</body>
</html>

src/ControlsTest/Views/Shared/_MvcControlsToolkitExampleLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -YourAppName</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @* Mvc Controls Toolkit Addition Start*@
    @{ await Html.RenderPartialAsync("_FallbackCss"); }
    @* Mvc Controls Toolkit Addition End*@  
</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - YourAppName</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @* Mvc Controls Toolkit Addition Start*@
    @{ await Html.RenderPartialAsync("_GlobalizationScriptsPartial"); }
    @{ await Html.RenderPartialAsync("_EnhancementFallbackPartial"); }
    @RenderSection("scripts", required: false)
    <script src="~/startupjs/startup.min.js"></script>
    @* Mvc Controls Toolkit Addition End*@
</body>
</html>